# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = 2

Vagrant.require_version '>= 1.6.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Vagrant virtual environment (box)
  config.vm.box = 'ubuntu/trusty64'

  # Update manually
  config.vm.box_check_update = false

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = 'https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160907.0.0/providers/virtualbox.box'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: '192.168.55.55'
  config.vm.network "forwarded_port", guest: 9200, host: 9200

  # The first argument is the path on the host to the actual folder.
  # The second argument is the path on the guest to mount the folder.
  # The optional third argument is a set of non-required options.
  config.vm.synced_folder(
    '../application',
    '/var/www/application',
    id: 'vagrant-root',
    owner: 'vagrant',
    group: 'www-data',
    mount_options: ['dmode=775,fmode=664']
  )
  config.vm.provider :virtualbox do |v|
    host = RbConfig::CONFIG['host_os']
    # Give VM 1/4 system memory
    if host =~ /darwin/
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024
    elsif host =~ /linux/
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i
    elsif host =~ /mswin|mingw|cygwin/
      # Windows code via https://github.com/rdsubhas/vagrant-faster
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end
    mem = mem / 1024 / 4
    v.customize ["modifyvm", :id, "--memory", mem]
    # allocate max 50% CPU
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    # v.customize ["modifyvm", :id, "--cpus", `awk "/^processor/ {++n} END {print n}" /proc/cpuinfo 2> /dev/null || sh -c 'sysctl hw.logicalcpu 2> /dev/null || echo ": 2"' | awk \'{print \$2}\' `.chomp ]
  end

  # A script to init out machine's environment
  config.vm.provision :shell, path: 'config/vagrant/install.sh'

  # Alternative: https://github.com/emyl/vagrant-triggers
  config.vm.provision :shell, path: 'config/vagrant/os_boot.sh', run: 'always'
end
