sudo: required
dist: trusty
group: edge

language: php

services:
  - mysql

addons:
    apt:
        sources:
        - deb http://archive.ubuntu.com/ubuntu/ trusty multiverse
        - deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse
        - deb http://archive.ubuntu.com/ubuntu/ trusty universe
        - deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe
        packages:
        - mysql-server-5.6
        - mysql-client-5.6
        - mysql-client-core-5.6
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation
    sauce_connect: true


cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:1.* squizlabs/php_codesniffer:2.* -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then phpunit --coverage-clover clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then phpunit ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpcs ; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls --coverage_clover=clover.xml -v ; fi

#notifications:
  # slack: token
  # hipchat: token
